# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

worldwarI = Happening.create( title: "World War I", body: "an epic war before the invention of mass warfare.", century: 1900s-2000s )
worldwarII = Happening.create( title: "World War II", body: "a war generated by a psycho, classic dictator.", century: 1900s-2000s )
dalailama = Happening.create( title: "The Dalai Lama", body: "inspiring person, more to come..", century: 2000s-now )
freud = Happening.create( title: "Frued, father of mordern advertising and more..", body: "Asshole that later felt his remorse", century: 1900s-2000s )


freudsbooks = WrittenImportance.create( title: "Freuds books", century: 1900s-2000s )
bible = WrittenImportance.create( title: "The Bible", author: "Multiple", body: "Interesting historic book", century: 0s-1700s )
koran = WrittenImportance.create( title: "The Koran", author: "Multiple", body: "Interesting historic book", century: 0s-1700s )


2000s-now = Century.create( title: "2000s to Now", happening: happening, writtenimportance: writtenimportance )
1900s-2000s = Century.create( title: "2000s to 1900s", happening: happening, writtenimportance: writtenimportance )
1900s-1800s = Century.create( title: "1900s to 1800s", happening: happening, writtenimportance: writtenimportance )
1800s-1700s = Century.create( title: "1800s to 1700s", happening: happening, writtenimportance: writtenimportance )
0s-1700s = Century.create( title: "Ancient History 0 to 1600s", happening: happening, writtenimportance: writtenimportance )

writtenimportances.each do |century|
  centuries.each do |century_title|
    if century = Century.find_by( title: century_title)
    end

    CenturyWrittenImportances.create( writtenimportance: writtenimportance, century: century )
  end
end

happenings.each do |century|
  centuries.each do |century_title|
    if century = Century.find_by( title: century_title)
    end

    CenturyHappenings.create( happening: happening, century: century )
  end
end
