# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

worldwarI = Happening.create( title: "World War I", body: "an epic war before the invention of mass warfare." )
worldwarII = Happening.create( title: "World War II", body: "a war generated by a psycho, classic dictator." )
dalailama = Happening.create( title: "The Dalai Lama", body: "inspiring person, more to come.." )
freud = Happening.create( title: "Frued, father of mordern advertising and more..", body: "Asshole that later felt his remorse")


freudsbooks = WrittenImportance.create( title: "Freuds books" )
bible = WrittenImportance.create( title: "The Bible", author: "Multiple", body: "Interesting historic book" )
koran = WrittenImportance.create( title: "The Koran", author: "Multiple", body: "Interesting historic book" )


2000s-now = Century.create( title: "2000s to Now")
1900s-2000s = Century.create( title: "2000s to 1900s" )
1900s-1800s = Century.create( title: "1900s to 1800s" )
1800s-1700s = Century.create( title: "1800s to 1700s" )
0s-1700s = Century.create( title: "Ancient History 0 to 1600s" )
